/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Highly optimized cryptographic range proof verification executed natively via Rust compiled assembly.
 * Integrates with V8 via NAPI-RS, eliminating thread serialization overhead.
 */
export declare function verifyBulletproofZk(commitmentBytes: Array<number>, proofBytes: Array<number>): boolean
